/**
 * Look Library
 * 24 preset looks across 5 collections.
 * Each look defines:
 *  - required: categories needed to fully achieve it
 *  - palette:  { skin, blush, eye, lip, bronze, highlight } hex colours
 *  - steps:    concise step-by-step notes
 *  - tags:     searchable style keywords
 */

export const COLLECTIONS = [
  { id: "everyday",   label: "Everyday",        emoji: "☀️" },
  { id: "seasonal",   label: "Seasonal 2025",   emoji: "🌸" },
  { id: "celebrity",  label: "Icon-Inspired",   emoji: "✦" },
  { id: "occasion",   label: "Occasion",        emoji: "🌙" },
  { id: "aesthetic",  label: "Aesthetic",       emoji: "🎨" },
];

export const LIBRARY_LOOKS = [

  // ════════════════════════════════════════════════════════
  // EVERYDAY
  // ════════════════════════════════════════════════════════
  {
    id: "clean-girl",
    collection: "everyday",
    name: "Clean Girl",
    subtitle: "The effortless standard",
    desc: "Glassy skin, fluffy brows, a wash of blush, and glossy lips. The look that made everyone buy a glass-skin routine.",
    palette: { skin: "#f0dcc8", blush: "#f5b8a8", eye: "#c4a882", lip: "#f0a898", bronze: "#c8a070", highlight: "#f8f0e0" },
    tags: ["Dewy", "Minimal", "Fresh", "Glassy", "Trendy"],
    intensity: "Sheer & Minimal",
    occasion: "Everyday",
    time: "8 min",
    difficulty: "Beginner",
    required: ["Foundation", "Concealer", "Blush", "Eyebrow", "Mascara", "Lip Gloss"],
    optional: ["Highlighter", "Setting Spray", "Primer"],
    steps: [
      "Moisturise and let skin fully absorb — dewy base is non-negotiable.",
      "Apply a sheer foundation or skin tint with fingers for the most natural finish.",
      "Concealer only where needed — no heavy coverage.",
      "Cream or powder blush swept high onto cheekbones and temples.",
      "Brush brows upward with a clear gel — no filling, just groomed.",
      "One coat of mascara, focusing on roots to lift.",
      "Glossy lip product — gloss alone or over a nude liner.",
      "Highlighter on the very top of cheekbones only.",
    ],
    tip: "The 'clean girl' look is 80% skincare. If your skin is prepped well, less product reads better.",
    celebrity: null,
    season: null,
  },

  {
    id: "five-minute",
    collection: "everyday",
    name: "5-Minute Face",
    subtitle: "The forever failsafe",
    desc: "Concealer, brows, mascara, lip balm. The exact four products every makeup artist packs first.",
    palette: { skin: "#e8c9a8", blush: "#f0c0a0", eye: "#8f7252", lip: "#e8a898", bronze: null, highlight: null },
    tags: ["Minimal", "Quick", "Natural", "Everyday"],
    intensity: "Natural Glow",
    occasion: "Everyday",
    time: "5 min",
    difficulty: "Beginner",
    required: ["Concealer", "Eyebrow", "Mascara"],
    optional: ["Tinted Moisturiser", "Blush", "Lip Gloss"],
    steps: [
      "Spot-conceal any redness or dark circles.",
      "Brush brows into shape with spoolie or clear gel.",
      "One to two coats of mascara.",
      "Tinted lip balm or gloss for a healthy flush of colour.",
    ],
    tip: "Concealer + brows + mascara = awake and polished. Everything else is bonus.",
    celebrity: null,
    season: null,
  },

  {
    id: "no-makeup",
    collection: "everyday",
    name: "No-Makeup Makeup",
    subtitle: "Skin that looks like skin",
    desc: "The art of looking like you're wearing nothing while actually wearing everything. Perfected skin, invisible base.",
    palette: { skin: "#e8d0b0", blush: "#f0c8b0", eye: "#d4bfa5", lip: "#d4a090", bronze: "#c0a070", highlight: "#f8ecd8" },
    tags: ["Natural", "Effortless", "Skin-First", "Invisible"],
    intensity: "Natural Glow",
    occasion: "Everyday",
    time: "15 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Blush", "Eyebrow", "Mascara"],
    optional: ["Bronzer", "Highlighter", "Setting Spray", "Lip Gloss"],
    steps: [
      "Skin-prep with SPF and let it fully set — 5 minutes minimum.",
      "Lightweight foundation or CC cream, applied with damp sponge.",
      "Concealer sheered out with ring finger — blend edges completely.",
      "Bronzer in the 3-position (forehead, cheeks, jaw) with a light hand.",
      "Cream blush on the apples, blended upward with fingers.",
      "Brow gel only — or lightly fill sparse areas with tiny strokes.",
      "Mascara on upper lashes only.",
      "Clear gloss or barely-there lip tint.",
      "Setting spray to meld all layers.",
    ],
    tip: "Every product should disappear — if you can see where it starts and ends, blend more.",
    celebrity: null,
    season: null,
  },

  {
    id: "office-polish",
    collection: "everyday",
    name: "Office Polish",
    subtitle: "Quiet authority",
    desc: "Foundation, defined brows, a neutral eye, and a mauve lip. Professional without trying, elegant without effort.",
    palette: { skin: "#d4a97a", blush: "#e8a090", eye: "#8f7252", lip: "#b07880", bronze: "#b08040", highlight: null },
    tags: ["Professional", "Polished", "Neutral", "Refined"],
    intensity: "Polished",
    occasion: "Work / Professional",
    time: "20 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Blush", "Eyeshadow", "Eyebrow", "Mascara", "Lipstick"],
    optional: ["Contour", "Setting Powder", "Primer", "Eyeliner"],
    steps: [
      "Primer on T-zone for all-day wear.",
      "Medium-coverage foundation blended with damp sponge.",
      "Concealer under eyes in inverted triangle, blended fully.",
      "Neutral taupe or warm brown eyeshadow — wash on lid, slightly deeper in crease.",
      "Thin eyeliner on upper lash line only.",
      "Well-defined brows with pencil, brushed through after.",
      "Mascara, two coats.",
      "Subtle blush swept toward temples.",
      "Matte or satin mauve lipstick — blot once.",
      "Setting powder on T-zone.",
    ],
    tip: "For professional looks, sharp brows do more work than any other product.",
    celebrity: null,
    season: null,
  },

  // ════════════════════════════════════════════════════════
  // SEASONAL 2025
  // ════════════════════════════════════════════════════════
  {
    id: "summer-bronze",
    collection: "seasonal",
    name: "Summer Bronze",
    subtitle: "Sun-kissed everywhere",
    desc: "Heavy bronzer, terracotta blush, sheer skin, and a coral lip. Summer 2025's biggest trend — looking like you just got back from the Amalfi Coast.",
    palette: { skin: "#d4a060", blush: "#e87848", eye: "#c08040", lip: "#d06038", bronze: "#a07030", highlight: "#f0c860" },
    tags: ["Bronze", "Terracotta", "Sun-kissed", "Summer", "Warm"],
    intensity: "Polished",
    occasion: "Everyday",
    time: "15 min",
    difficulty: "Beginner",
    required: ["Bronzer", "Blush", "Mascara", "Foundation"],
    optional: ["Highlighter", "Lip Gloss", "Setting Spray"],
    steps: [
      "Sheer or light foundation — let skin breathe through it.",
      "Bronzer everywhere the sun would touch: forehead, nose, cheeks, chin.",
      "Terracotta or peachy-brick blush layered on top of bronzer on cheeks.",
      "Gold or bronze eyeshadow wash on the lid.",
      "Mascara on upper lashes only.",
      "Coral or peachy-nude lip gloss.",
      "Gold highlighter on the highest point of cheekbones.",
    ],
    tip: "For this look, bronzer goes on before blush — not after.",
    celebrity: null,
    season: "Summer 2025",
  },

  {
    id: "glazed-donut",
    collection: "seasonal",
    name: "Glazed Donut",
    subtitle: "Hailey Bieber's signature",
    desc: "The look that broke the internet: ultra-glossy skin, vanilla-glazed highlight, milky nails, and barely-there lips. All glow, no drama.",
    palette: { skin: "#f0e0c8", blush: "#f8d0c0", eye: "#f0dcc8", lip: "#f0c8b8", bronze: null, highlight: "#fffff0" },
    tags: ["Glazed", "Glossy", "Dewy", "Viral", "Minimal"],
    intensity: "Sheer & Minimal",
    occasion: "Everyday",
    time: "10 min",
    difficulty: "Beginner",
    required: ["Highlighter", "Lip Gloss", "Concealer"],
    optional: ["Setting Spray", "Skin Tint", "Blush"],
    steps: [
      "Moisturise heavily — this look is 90% skincare.",
      "Skin tint or nothing — let real skin show.",
      "Concealer only under eyes if needed, sheered with damp sponge.",
      "Cream highlighter pressed onto cheekbones, nose bridge, cupid's bow.",
      "Setting spray or facial mist for the wet, glazed finish.",
      "Clear or milky-sheer gloss on lips.",
    ],
    tip: "Press highlighter with your ring finger — the warmth melts it into skin for a real glow.",
    celebrity: "Hailey Bieber",
    season: "2025 Trending",
  },

  {
    id: "spring-pastels",
    collection: "seasonal",
    name: "Spring Pastels",
    subtitle: "Cherry blossoms in makeup form",
    desc: "Soft lavender or pink eyeshadow, a rosy blush, and a sheer berry lip. Spring 2025's colour trend in wearable form.",
    palette: { skin: "#f0d8c8", blush: "#f5b8c8", eye: "#d4a8c8", lip: "#c88098", bronze: null, highlight: "#f8e0f0" },
    tags: ["Pastel", "Spring", "Feminine", "Colourful", "Sweet"],
    intensity: "Natural Glow",
    occasion: "Everyday",
    time: "15 min",
    difficulty: "Intermediate",
    required: ["Eyeshadow", "Blush", "Mascara", "Lipstick"],
    optional: ["Primer", "Highlighter", "Eyeliner", "Concealer"],
    steps: [
      "Light concealer or skin tint as base.",
      "Pastel pink, lavender, or lilac eyeshadow — packed on lid, nothing in crease.",
      "White or champagne shadow on inner corner to brighten.",
      "Thin brown liner on the waterline for softness.",
      "Rose-toned blush swept wide across cheeks.",
      "Sheer berry or rose lip colour.",
      "Pearl or iridescent highlighter on cheekbones.",
    ],
    tip: "Pastel eyeshadow with cool-toned pink blush and lip creates cohesion instantly.",
    celebrity: null,
    season: "Spring 2025",
  },

  {
    id: "holiday-glam",
    collection: "seasonal",
    name: "Holiday Glam",
    subtitle: "The party season look",
    desc: "Smokey eye, champagne highlight, sculpted cheeks, and the boldest lip of the year. This is the look for December.",
    palette: { skin: "#c4a882", blush: "#b07060", eye: "#4a2142", lip: "#900030", bronze: "#906030", highlight: "#f0d060" },
    tags: ["Glam", "Holiday", "Festive", "Dramatic", "Gold"],
    intensity: "Full Glam",
    occasion: "Party / Event",
    time: "40 min",
    difficulty: "Advanced",
    required: ["Foundation", "Concealer", "Eyeshadow", "Eyeliner", "Mascara", "Eyebrow", "Blush", "Contour", "Highlighter", "Lipstick"],
    optional: ["Primer", "Setting Powder", "Setting Spray", "Eye Primer", "Lip Liner"],
    steps: [
      "Full-coverage primer + foundation. Bake under eyes.",
      "Colour correct and conceal — flawless base is the priority.",
      "Contour and sculpt cheekbones, temples, jaw.",
      "Deep berry or plum shadow in outer V, gold on lid, champagne on inner corner.",
      "Graphic liner or thick wing.",
      "Three coats of mascara, let each dry.",
      "Bold brows — slightly darker than normal.",
      "Deep blush for warmth.",
      "Gold or champagne highlight on all high points.",
      "Red or deep berry lip — liner first, two coats, blot.",
      "Setting spray to lock everything.",
    ],
    tip: "For glam longevity: bake, don't just powder. The difference is significant.",
    celebrity: null,
    season: "Holiday 2025",
  },

  // ════════════════════════════════════════════════════════
  // CELEBRITY / ICON-INSPIRED
  // ════════════════════════════════════════════════════════
  {
    id: "old-hollywood",
    collection: "celebrity",
    name: "Old Hollywood",
    subtitle: "Audrey Hepburn energy",
    desc: "Winged liner, defined brows, porcelain skin, and a classic red lip. The most iconic makeup formula ever created.",
    palette: { skin: "#f0e0c8", blush: "#f0c0b0", eye: "#1a0a00", lip: "#c02020", bronze: null, highlight: null },
    tags: ["Classic", "Vintage", "Red Lip", "Dramatic", "Timeless"],
    intensity: "Bold & Defined",
    occasion: "Special Occasion",
    time: "25 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Eyeliner", "Eyebrow", "Mascara", "Lipstick", "Lip Liner"],
    optional: ["Setting Powder", "Blush", "Primer"],
    steps: [
      "Flawless, matte foundation — no skin showing through.",
      "Heavy concealer under eyes, set with powder.",
      "Defined arched brows — slightly bold.",
      "No eyeshadow or the faintest wash of neutral.",
      "Classic winged liner — practise the flick first.",
      "Two to three coats of volumising mascara.",
      "Soft peach or neutral blush — barely-there.",
      "Lip liner mapping the exact lip shape.",
      "Two coats of red lipstick. Blot, reapply.",
    ],
    tip: "The red lip and liner do all the work. Keep everything else neutral and precise.",
    celebrity: "Audrey Hepburn / Marilyn Monroe",
    season: null,
  },

  {
    id: "sza-glazed",
    collection: "celebrity",
    name: "Glazed Skin",
    subtitle: "SZA's signature dewy glow",
    desc: "Luminous base, sculpted cheeks, defined eyes, and a glassy lip. Rich, radiant, and completely effortless-looking.",
    palette: { skin: "#a07040", blush: "#a06040", eye: "#604020", lip: "#c09060", bronze: "#805020", highlight: "#d4a040" },
    tags: ["Glazed", "Radiant", "Sculpted", "Rich", "Glow"],
    intensity: "Polished",
    occasion: "Date Night",
    time: "25 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Contour", "Bronzer", "Blush", "Highlighter", "Mascara", "Eyebrow"],
    optional: ["Lip Gloss", "Eyeliner", "Setting Spray"],
    steps: [
      "Luminous or serum foundation applied with damp sponge.",
      "Concealer blended seamlessly — no harsh triangle.",
      "Warm contour under cheekbones, temples, jaw.",
      "Rich golden bronze on the cheeks and nose.",
      "Peachy-terracotta blush on the apples.",
      "Gold or copper highlighter — cheekbones, nose bridge, inner corners.",
      "Warm brown eyeshadow wash on the lid.",
      "Defined brows, natural-looking.",
      "Glassy nude gloss.",
    ],
    tip: "Layering bronze + blush + highlight in the same warm family is the secret to this 3D radiance.",
    celebrity: "SZA",
    season: null,
  },

  {
    id: "bella-hadid-model",
    collection: "celebrity",
    name: "Model Off-Duty",
    subtitle: "Bella Hadid's off-duty look",
    desc: "Barely-there base, heavily defined brows, a bold liner flick, and a matte nude lip. Effortless in a way that takes actual effort.",
    palette: { skin: "#d4b888", blush: "#c09080", eye: "#1a0a00", lip: "#b09070", bronze: "#a07840", highlight: null },
    tags: ["Editorial", "Model", "Defined", "Minimal", "Cool"],
    intensity: "Natural Glow",
    occasion: "Everyday",
    time: "15 min",
    difficulty: "Intermediate",
    required: ["Concealer", "Eyebrow", "Eyeliner", "Mascara", "Lipstick"],
    optional: ["Foundation", "Bronzer", "Setting Spray"],
    steps: [
      "Skip foundation — use concealer only where needed.",
      "Strong, defined brows — this look lives and dies on the brow.",
      "Graphic or thick liner flick, no eyeshadow.",
      "Mascara — lower lashes too for a vintage edge.",
      "No blush or very subtle bronzer.",
      "Matte nude or barely-there lip.",
    ],
    tip: "The strong brow + graphic liner combination is what makes this look. Both must be sharp.",
    celebrity: "Bella Hadid",
    season: null,
  },

  {
    id: "zendaya-red-carpet",
    collection: "celebrity",
    name: "Red Carpet Ready",
    subtitle: "Zendaya-level occasion makeup",
    desc: "Flawless sculpted base, defined crease, and a statement bold lip. Every element is intentional and high-impact.",
    palette: { skin: "#c09060", blush: "#b07060", eye: "#704030", lip: "#a02040", bronze: "#905030", highlight: "#d4a050" },
    tags: ["Red Carpet", "Dramatic", "Sculpted", "Bold", "Statement"],
    intensity: "Full Glam",
    occasion: "Special Occasion",
    time: "45 min",
    difficulty: "Advanced",
    required: ["Foundation", "Concealer", "Contour", "Blush", "Eyeshadow", "Eyeliner", "Mascara", "Eyebrow", "Highlighter", "Lipstick", "Lip Liner"],
    optional: ["Primer", "Setting Powder", "Setting Spray", "Eye Primer", "Color Corrector"],
    steps: [
      "Full-face prep: skincare, primer, colour correct.",
      "Full-coverage foundation blended perfectly.",
      "Bake under eyes and any high-coverage areas.",
      "Contour precisely — cheekbones, temples, nose, jaw.",
      "Warm blush layered on top of contour.",
      "Gold highlight on cheekbones, inner corners, cupid's bow.",
      "Warm brown shadow in crease, champagne on lid.",
      "Precise liner + wing.",
      "Bold brows.",
      "Three-layer lip with liner, two coats colour, blot.",
      "Finishing spray.",
    ],
    tip: "Red carpet makeup is about longevity as much as beauty — prep and set at every stage.",
    celebrity: "Zendaya",
    season: null,
  },

  // ════════════════════════════════════════════════════════
  // OCCASION
  // ════════════════════════════════════════════════════════
  {
    id: "wedding-guest",
    collection: "occasion",
    name: "Wedding Guest",
    subtitle: "Beautiful but not the bride",
    desc: "Polished, photo-ready, and long-lasting. Warm neutrals, defined eyes, and a flattering pink-nude lip.",
    palette: { skin: "#d4a97a", blush: "#e8a090", eye: "#a08060", lip: "#c08880", bronze: "#b08040", highlight: "#f0d890" },
    tags: ["Wedding", "Occasion", "Elegant", "Polished", "Photo-ready"],
    intensity: "Polished",
    occasion: "Special Occasion",
    time: "35 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Eyeshadow", "Mascara", "Eyebrow", "Blush", "Lipstick"],
    optional: ["Highlighter", "Contour", "Primer", "Setting Spray", "Setting Powder"],
    steps: [
      "Full-coverage but natural foundation — you're in photos.",
      "Flawless concealer under eyes.",
      "Warm taupe crease, champagne on lid.",
      "Subtle liner on upper lash line.",
      "Full mascara with individual lashes optional.",
      "Defined but natural brows.",
      "Peachy-rose blush for warmth.",
      "Highlight on cheekbones.",
      "Pink-nude or mauve lip — classic and always right.",
    ],
    tip: "Flash photography washes out colour — go 20% more pigmented than feels right at home.",
    celebrity: null,
    season: null,
  },

  {
    id: "date-night",
    collection: "occasion",
    name: "Date Night",
    subtitle: "One focal point, perfectly done",
    desc: "Either a smokey eye with a nude lip, or a bold lip with neutral eyes. Pick one. Do it right. That's the rule.",
    palette: { skin: "#c4a882", blush: "#c07868", eye: "#7d3f71", lip: "#c03050", bronze: "#a07040", highlight: "#f0d080" },
    tags: ["Date", "Romantic", "Bold", "Evening", "Sultry"],
    intensity: "Bold & Defined",
    occasion: "Date Night",
    time: "30 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Eyeshadow", "Mascara", "Eyebrow", "Blush", "Lipstick"],
    optional: ["Contour", "Highlighter", "Eyeliner", "Setting Spray"],
    steps: [
      "Smooth, polished foundation.",
      "Seamless concealer.",
      "CHOOSE: Smokey or bold lip (not both).",
      "Smokey option: deep shadow in outer V, medium on lid, light inner corner, liner.",
      "Bold lip option: neutral shadow, liner + two coats lipstick.",
      "Defined brows.",
      "Mascara — two to three coats.",
      "Subtle sculpt — blush and light contour.",
      "Setting spray for longevity.",
    ],
    tip: "The rule of one focal point isn't a limitation — it's what separates a great date look from an overwhelming one.",
    celebrity: null,
    season: null,
  },

  {
    id: "festival",
    collection: "occasion",
    name: "Festival",
    subtitle: "Bold, fun, and waterproof",
    desc: "Graphic liner, colourful shadow, and bold lips. Sweat-resistant, photo-ready, and fully expressive.",
    palette: { skin: "#c4a882", blush: "#e87890", eye: "#7060c0", lip: "#d03080", bronze: "#a07848", highlight: "#f8d050" },
    tags: ["Festival", "Graphic", "Colourful", "Bold", "Creative"],
    intensity: "Full Glam",
    occasion: "Party / Event",
    time: "35 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Eyeshadow", "Eyeliner", "Mascara", "Blush", "Lipstick"],
    optional: ["Glitter", "Loose Pigment", "Setting Spray", "Highlighter"],
    steps: [
      "Long-wear primer and foundation — you're outdoors.",
      "Graphic liner — cat eye, floating liner, or geometric shape.",
      "Bold colour on the lid: electric, unexpected, maximalist.",
      "Glitter or pigment on inner corner or lid.",
      "Strong, defined mascara.",
      "Bright or sculptural blush placement.",
      "Bold lip — liner and two coats.",
      "Setting spray — a lot of it.",
    ],
    tip: "Waterproof everything you own for festivals. Set spray twice. Check a mirror at 2-hour intervals.",
    celebrity: null,
    season: null,
  },

  {
    id: "school-fresh",
    collection: "occasion",
    name: "School / College",
    subtitle: "Quick and effortless",
    desc: "Concealer, brow gel, mascara, blush, and a tinted lip. You're out the door in 8 minutes and you look great.",
    palette: { skin: "#e8d0b0", blush: "#f5c0a8", eye: "#c4a882", lip: "#e8a898", bronze: null, highlight: null },
    tags: ["School", "Quick", "Natural", "Student", "Easy"],
    intensity: "Natural Glow",
    occasion: "School / College",
    time: "8 min",
    difficulty: "Beginner",
    required: ["Concealer", "Eyebrow", "Mascara", "Blush"],
    optional: ["Lip Gloss", "Setting Spray", "BB Cream"],
    steps: [
      "BB cream or nothing if skin is clear.",
      "Concealer on spots or dark circles only.",
      "Brow gel — 30 seconds.",
      "Mascara — one coat.",
      "Cream blush tapped on with fingers.",
      "Tinted lip balm or clear gloss.",
    ],
    tip: "Cream products apply faster than powders and look more natural in one layer.",
    celebrity: null,
    season: null,
  },

  // ════════════════════════════════════════════════════════
  // AESTHETICS
  // ════════════════════════════════════════════════════════
  {
    id: "dark-feminine",
    collection: "aesthetic",
    name: "Dark Feminine",
    subtitle: "Magnetic and moody",
    desc: "Sculpted cheeks, deep berry lips, and a smokey eye. This look commands attention without asking for it.",
    palette: { skin: "#8f7252", blush: "#803050", eye: "#4a2142", lip: "#700030", bronze: "#704030", highlight: "#c08040" },
    tags: ["Dark", "Moody", "Bold", "Sultry", "Dramatic"],
    intensity: "Full Glam",
    occasion: "Party / Event",
    time: "40 min",
    difficulty: "Advanced",
    required: ["Foundation", "Concealer", "Contour", "Blush", "Eyeshadow", "Eyeliner", "Mascara", "Eyebrow", "Lipstick", "Lip Liner"],
    optional: ["Bronzer", "Highlighter", "Setting Powder", "Eye Primer"],
    steps: [
      "Full-coverage, flawless base.",
      "Heavy contour — cheekbones, jaw, temples.",
      "Deep berry or wine blush — high on cheekbones.",
      "Dark plum or deep taupe shadow — outer V, crease, lower lash line.",
      "Tight-line upper and lower waterline with kohl.",
      "Heavy mascara — both lashes.",
      "Strong brows.",
      "Deep berry or wine lip — liner fills entire lip first.",
      "Bronze highlight only if skin tone is deeper.",
    ],
    tip: "Dark feminine works best when the base is completely flawless — the drama needs a perfect canvas.",
    celebrity: null,
    season: null,
  },

  {
    id: "soft-glam",
    collection: "aesthetic",
    name: "Soft Glam",
    subtitle: "Warm, polished, and always flattering",
    desc: "The timeless signature: warm eyeshadow, defined lashes, flushed cheeks, and a nude-mauve lip. Works on everyone.",
    palette: { skin: "#d4a97a", blush: "#e8956a", eye: "#b87aaa", lip: "#c08080", bronze: "#b08040", highlight: "#f0d890" },
    tags: ["Soft", "Warm", "Classic", "Glam", "Feminine"],
    intensity: "Polished",
    occasion: "Date Night",
    time: "30 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Eyeshadow", "Mascara", "Eyebrow", "Blush", "Lipstick"],
    optional: ["Contour", "Bronzer", "Highlighter", "Eyeliner", "Setting Spray"],
    steps: [
      "Polished, medium-coverage foundation.",
      "Seamless concealer.",
      "Transition shade in crease (mid-brown or taupe).",
      "Warm eyeshadow on lid (rose, copper, or champagne).",
      "Darker shade to define outer corner.",
      "Light liner on upper lash line.",
      "Full mascara.",
      "Defined, groomed brows.",
      "Peachy blush swept upward.",
      "Soft highlighter.",
      "Nude-mauve or rose-brown lip.",
    ],
    tip: "The soft glam eye works best with shades that are all from the same warm family — mix undertones and it loses its cohesion.",
    celebrity: null,
    season: null,
  },

  {
    id: "quiet-luxury",
    collection: "aesthetic",
    name: "Quiet Luxury",
    subtitle: "Old money, new energy",
    desc: "Near-invisible makeup done with expensive-looking restraint. Porcelain base, barely-there blush, natural brows, and the palest lip.",
    palette: { skin: "#f0e0c8", blush: "#f0d0c0", eye: "#d4bfa5", lip: "#e8c8b8", bronze: null, highlight: "#f8f0e0" },
    tags: ["Quiet Luxury", "Minimal", "Refined", "Expensive", "Subtle"],
    intensity: "Sheer & Minimal",
    occasion: "Work / Professional",
    time: "15 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Concealer", "Eyebrow", "Blush"],
    optional: ["Highlighter", "Mascara", "Setting Spray", "Primer"],
    steps: [
      "Expensive-feeling skin prep — this look is all texture.",
      "Sheered-out or skin-tint foundation. NO powder.",
      "Minimal concealer only where truly needed.",
      "Groomed, natural brows — no bold filling.",
      "No eye makeup or the faintest wash of cream shadow.",
      "Barely-there blush — cream, fingers, sheered.",
      "Pearl highlighter pressed into cheekbones.",
      "A nude lip that matches your natural colour almost exactly.",
    ],
    tip: "The secret to quiet luxury: spend the time on skincare and application technique, not product quantity.",
    celebrity: null,
    season: null,
  },

  {
    id: "y2k-butterfly",
    collection: "aesthetic",
    name: "Y2K Glam",
    subtitle: "Nostalgia peak aesthetic",
    desc: "Frosty pink lips, shimmery glitter lid, graphic liner, and over-lined lips. Britney circa 2001 — but make it modern.",
    palette: { skin: "#e8d0c0", blush: "#f5b0c8", eye: "#c0a0e0", lip: "#f0b0d8", bronze: null, highlight: "#f8f0c0" },
    tags: ["Y2K", "Retro", "Glitter", "Pink", "Fun", "Playful"],
    intensity: "Bold & Defined",
    occasion: "Party / Event",
    time: "30 min",
    difficulty: "Intermediate",
    required: ["Foundation", "Eyeshadow", "Eyeliner", "Mascara", "Lip Gloss", "Lip Liner"],
    optional: ["Glitter", "Loose Pigment", "Blush", "Highlighter"],
    steps: [
      "Light, dewy base — Y2K preferred a bare-ish finish.",
      "Frosty or shimmer eyeshadow all over the lid.",
      "Glitter on the centre of the lid.",
      "Lower lash line liner or sparkle liner.",
      "Slightly over-lined lips with liner.",
      "Frosty pink or clear gloss — the glossier the better.",
      "Pink blush high on cheeks.",
      "Iridescent highlight.",
    ],
    tip: "The more shimmer the better for Y2K. If it glitters, it belongs on this look.",
    celebrity: "Britney Spears / Paris Hilton",
    season: null,
  },

  {
    id: "indie-sleaze",
    collection: "aesthetic",
    name: "Indie Sleaze",
    subtitle: "Deliberately undone",
    desc: "Smudged liner, barely-there base, and lived-in texture. The beauty equivalent of a vintage band tee.",
    palette: { skin: "#d4b890", blush: "#b08070", eye: "#302010", lip: "#a07060", bronze: "#906040", highlight: null },
    tags: ["Indie", "Grunge", "Lived-in", "Edgy", "Cool"],
    intensity: "Natural Glow",
    occasion: "Party / Event",
    time: "10 min",
    difficulty: "Beginner",
    required: ["Eyeliner", "Mascara", "Concealer"],
    optional: ["Lip Gloss", "Blush", "Foundation"],
    steps: [
      "Nothing on skin, or a trace of concealer.",
      "Dark kohl liner — applied and then smudged with finger.",
      "Lower lash line smudged too.",
      "Mascara, slightly smudgy-looking.",
      "Berry or nude-brown lip.",
      "Optional: a touch of cream blush on nose and cheeks.",
    ],
    tip: "The 'deliberately undone' look is harder than it looks — the liner has to be the right kind of smudged, not just sloppy.",
    celebrity: null,
    season: null,
  },

  {
    id: "coquette",
    collection: "aesthetic",
    name: "Coquette",
    subtitle: "Bow-adorned, blush-drenched",
    desc: "Exaggerated blush, doe eyes, and the palest lip. TikTok's most aesthetic look — soft, feminine, and intentionally romantic.",
    palette: { skin: "#f5e0d8", blush: "#f5a0b8", eye: "#f0b0c8", lip: "#f0d0d8", bronze: null, highlight: "#fff0f8" },
    tags: ["Coquette", "Feminine", "Blush", "Romantic", "TikTok"],
    intensity: "Natural Glow",
    occasion: "Everyday",
    time: "20 min",
    difficulty: "Beginner",
    required: ["Blush", "Mascara", "Eyebrow", "Concealer"],
    optional: ["Lip Gloss", "Highlighter", "Eyeshadow"],
    steps: [
      "Sheer base — skin should look natural.",
      "Heavy, exaggerated blush — across the nose and cheeks (sunburn blush).",
      "Soft pink or mauve shadow on the lower lash line for doe eyes.",
      "Soft natural brows — never harsh.",
      "Full lower lash mascara for the doe-eyed effect.",
      "Pale pink gloss or nothing on lips.",
      "Pearl or lavender highlight on cheekbones.",
    ],
    tip: "Coquette blush goes on the nose too — that's the defining feature that separates it from regular blush.",
    celebrity: null,
    season: "2025 Trending",
  },
];

// Derived helpers
export function getLooksByCollection(collectionId) {
  return collectionId === "all"
    ? LIBRARY_LOOKS
    : LIBRARY_LOOKS.filter(l => l.collection === collectionId);
}

export function searchLooks(query) {
  const q = query.toLowerCase();
  return LIBRARY_LOOKS.filter(l =>
    l.name.toLowerCase().includes(q) ||
    l.tags.some(t => t.toLowerCase().includes(q)) ||
    l.desc.toLowerCase().includes(q) ||
    l.occasion.toLowerCase().includes(q) ||
    (l.celebrity && l.celebrity.toLowerCase().includes(q)) ||
    (l.season && l.season.toLowerCase().includes(q))
  );
}
