export const PAGES = {
  HOME:      "home",
  INVENTORY: "inventory",
  PROFILE:   "profile",
  GENERATE:  "generate",
  LIBRARY:   "library",
  FIX:       "fix",
  PAIRINGS:  "pairings",
  LEARN:     "learn",
  EVALUATE:  "evaluate",
  TOOLS:     "tools",
  WISHLIST:  "wishlist",
  DIARY:     "diary",
  ROUTINE:   "routine",
  EXPIRY:    "expiry",
  CONCERNS:  "concerns",
  SEASONAL:  "seasonal",
  DUPES:     "dupes",
  PALETTE:   "palette",
};
