export const TRENDING_LOOKS = [
  {
    id: "clean-girl",
    name: "Clean Girl",
    season: "Trending",
    desc: "Glassy skin, brushed brows, and a lip-glossed pout. Less is effortlessly more.",
    palette: ["#f5d5c0", "#e8b4a0", "#c4a882", "#f0c8b0"],
    keywords: ["Dewy", "Minimal", "Natural"],
    intensity: "Sheer & Minimal",
    occasion: "Everyday",
  },
  {
    id: "soft-glam",
    name: "Soft Glam",
    season: "Timeless",
    desc: "Warm eyeshadow, defined lashes, and a nude-mauve lip. Classic and always flattering.",
    palette: ["#c4a882", "#b87aaa", "#8f7252", "#e8956a"],
    keywords: ["Warm", "Polished", "Feminine"],
    intensity: "Polished",
    occasion: "Date Night",
  },
  {
    id: "dark-feminine",
    name: "Dark Feminine",
    season: "Autumn",
    desc: "Deep berries, smokey liner, and sculpted skin. Bold, moody, and magnetic.",
    palette: ["#7d3f71", "#4a2142", "#9f1239", "#4d3c28"],
    keywords: ["Bold", "Moody", "Sultry"],
    intensity: "Full Glam",
    occasion: "Party / Event",
  },
  {
    id: "no-makeup",
    name: "No-Makeup Makeup",
    season: "Evergreen",
    desc: "Skin that looks like skin — perfected. Barely-there colour with maximum freshness.",
    palette: ["#f2ece5", "#e3d5c5", "#d4bfa5", "#fbe8de"],
    keywords: ["Natural", "Effortless", "Fresh"],
    intensity: "Natural Glow",
    occasion: "Natural / No-Makeup",
  },
  {
    id: "old-money",
    name: "Old Money",
    season: "Trending",
    desc: "Quiet luxury — porcelain skin, barely-there blush, and a barely-tinted lip.",
    palette: ["#f5e6d3", "#e3d5c5", "#c4a882", "#fdf4f0"],
    keywords: ["Minimal", "Refined", "Elegant"],
    intensity: "Sheer & Minimal",
    occasion: "Work / Professional",
  },
  {
    id: "y2k-glam",
    name: "Y2K Glam",
    season: "Comeback",
    desc: "Glossy lids, frosty pink lips, and graphic liner. Nostalgia never looked this good.",
    palette: ["#fecdd3", "#b87aaa", "#fb7185", "#f0e3ed"],
    keywords: ["Playful", "Shiny", "Retro"],
    intensity: "Bold & Defined",
    occasion: "Party / Event",
  },
];

export const SOCIAL_PROOF = [
  {
    name: "Amira S.",
    handle: "@amira.glows",
    avatar: "A",
    avatarColor: "#b87aaa",
    text: "I literally stopped buying random products. The gap analysis showed me I was missing a setting spray and that's why my look never lasted. Game changer.",
    look: "Soft Glam",
  },
  {
    name: "Priya K.",
    handle: "@priyamakeup",
    avatar: "P",
    avatarColor: "#e8956a",
    text: "The AI evaluation told me my blush was going on too low — I'd been doing it wrong for 3 years. One small change and the difference is insane.",
    look: "Clean Girl",
  },
  {
    name: "Sofia M.",
    handle: "@sofiabella",
    avatar: "S",
    avatarColor: "#fb7185",
    text: "I own 47 products and had no idea how to use them together. Now I get a complete routine every morning in 30 seconds. This is honestly witchcraft.",
    look: "Dark Feminine",
  },
  {
    name: "Zara T.",
    handle: "@zarabeauty_",
    avatar: "Z",
    avatarColor: "#7d3f71",
    text: "Finally an app that matches products to MY undertone and face shape. Not generic advice — actually personalised. The fix engine saved my foundation shade.",
    look: "Polished",
  },
];

export const MARQUEE_ITEMS = [
  "✦ Personalised to your skin",
  "🌸 No login needed",
  "✨ AI-powered analysis",
  "💋 Works with products you own",
  "✦ 100% in your browser",
  "🌸 Zero data shared",
  "✨ Free forever",
  "💋 Smart pairings engine",
  "✦ Fix any makeup issue",
  "🌸 Trusted by beauty lovers",
];
